dependencies:
  - name: dask-distributed
    repository: https://kubernetes-charts.storage.googleapis.com/
    version: 2.0.0
    tags:
      - dask-distributed
      - dask
  - name: spark
    repository: https://kubernetes-charts.storage.googleapis.com/
    version: 0.1.4
    tags:
      - spark
